# Generated by Django 5.0.3 on 2024-04-01 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='API_Data',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('datum', models.DateField()),
                ('zeit', models.TimeField()),
                ('temperatur', models.DecimalField(decimal_places=2, max_digits=5)),
                ('gewicht', models.DecimalField(decimal_places=2, max_digits=5)),
                ('notiz', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LeerGewicht',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('leer_gewicht', models.FloatField()),
            ],
        ),
    ]
