# Generated by Django 5.0.3 on 2024-04-02 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='api_data',
            options={'verbose_name': 'API Daten', 'verbose_name_plural': 'API Daten'},
        ),
        migrations.AlterModelOptions(
            name='leergewicht',
            options={'verbose_name': 'Leer Gewicht', 'verbose_name_plural': 'Leer Gewichte'},
        ),
        migrations.AlterField(
            model_name='leergewicht',
            name='leer_gewicht',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
